# Generated by Django 5.2 on 2025-04-09 10:41

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(max_length=255)),
                ('reg_due_date', models.DateTimeField()),
                ('concluded', models.BooleanField(default=False)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='edition')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('Location', models.TextField()),
                ('photo_entry', models.ImageField(upload_to='uploads/entries')),
                ('theme_of_entry', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photography_experience', models.CharField(choices=[('Beginer', 'beginer'), ('Intermediate', 'intermediate'), ('Professional', 'professional')], max_length=255)),
                ('profile_picture', models.ImageField(upload_to='uploads/user_images')),
                ('instagram_username', models.CharField(max_length=255)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', related_query_name='entries', to='app.competition')),
            ],
        ),
    ]
