# Generated by Django 5.2 on 2025-04-10 07:57

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_competition_slug_alter_entry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='id',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
