# Generated by Django 5.2 on 2025-04-11 15:57

import datetime
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_competition_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='entry',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 11, 15, 57, 41, 159636, tzinfo=datetime.timezone.utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
