# Generated by Django 5.2 on 2025-04-11 16:13

import datetime
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_entry_options_entry_created_entry_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='competition',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 11, 16, 13, 35, 340539, tzinfo=datetime.timezone.utc), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
