# Generated by Django 5.2 on 2025-04-13 18:56

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_competition_options_competition_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=django_extensions.db.fields.RandomCharField(blank=True, editable=False, include_alpha=False, length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
