# Generated by Django 5.2 on 2025-04-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_entry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
