# Generated by Django 5.2 on 2025-04-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_entry_photo_entry_entry_submitted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='profile_picture',
            field=models.ImageField(upload_to='shutter9ja/uploads/entries/user_images/'),
        ),
    ]
