# Generated by Django 5.2 on 2025-04-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_entry_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=models.ImageField(upload_to='shutter9ja/uploads/entries/images/'),
        ),
    ]
