# Generated by Django 5.2 on 2025-04-22 12:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_entry_profile_picture_alter_entryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=models.ImageField(upload_to=app.models.entry_image_upload_path),
        ),
    ]
