# Generated by Django 5.2 on 2025-04-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_entry_profile_picture_alter_entryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=models.ImageField(upload_to='entry_images'),
        ),
    ]
