# Generated by Django 5.2 on 2025-04-22 20:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_entry_profile_picture_alter_entryimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
